spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: dkhj1rghl

gcs:
  bucket-name: cs-linkedin-prod
  access-account: >
    {
      "type": "service_account",
      "project_id": "kubernetes-projects-441716",
      "universe_domain": "googleapis.com"
    }
